# docker-compose -p dev -f local-dev.yml up -d
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/mysql/datadir:/var/lib/mysql
    mem_limit: 512M
    cpus: 1.0
  
  mariadb:
    image: mariadb
    container_name: mariadb
    #restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/mariadb/datadir:/var/lib/mysql
    mem_limit: 512M
    cpus: 1.0
  
  redis:
    image: redis
    container_name: redis
    #restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
      REDIS_PASSWORD: 123456
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    mem_limit: 512M
    cpus: 1.0
      
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    mem_limit: 512M
    cpus: 1.0