# docker-compose -p dev -f local-dev.yml up -d
version: '3.1'

services:

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    #restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/mysql/datadir:/var/lib/mysql
  
  mariadb:
    image: mariadb
    container_name: mariadb
    #restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123456
    volumes:
      - ./volumes/mariadb/datadir:/var/lib/mysql
  
  redis:
    image: redis
    container_name: redis
    #restart: always
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
      
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data