# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MARIADB_ROOT_PASSWORD: 123456

  mariadb-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080