version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    #restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
    command: --wiredTigerCacheSizeGB 4 --auth # 限制内存大小, 需要认证
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin