server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://172.19.0.2:5432/thingsboard
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000

# ===== TimescaleDB/SQL模式 =====
database:
  ts:
    type: timescale
  ts_latest:
    type: timescale

install:
  data_dir: /data

logging:

  file:
    name: /logs/thingsboard.log

  level:
    root: INFO
    org.thingsboard: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
