server {

	listen 80;

	location /lua {
		default_type text/plain;

		content_by_lua_block {
			ngx.say("Hello OpenResty!")
			ngx.say("URI: ", ngx.var.uri)
		}
	}

	# 静态文件目录（可用来放 m3u8、ts）
	location / {
		root /usr/local/openresty/nginx/html;
		index index.html;
	}
}