# docker compose -p seata2 up -d
version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:2.0.0
    hostname: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
    mem_limit: 512M
    cpus: 1.0