services:
  emqx:
    image: emqx:latest
    container_name: emqx
    hostname: docker.emqx.dev
    ports:
      - "18083:18083"
      - "1883:1883"
    volumes:
      - ./plugins:/opt/emqx/plugins:rw
      - ./data:/opt/emqx/data:rw
      - ./log:/opt/emqx/log:rw
      - ./emqx.conf:/opt/emqx/etc/emqx.conf:ro
    environment:
      - EMQX_HOST=docker.emqx.dev
      - EMQX_NODE__DATA_DIR="data"
      - EMQX_LOG__FILE__DEFAULT__ENABLE=true
      - EMQX_LOG__CONSOLE__ENABLE=false
      - EMQX_DASHBOARD__LISTENERS__HTTP__BIND=18083
      - EMQX_LISTENERS__SSL__DEFAULT=marked_for_deletion
      - EMQX_LISTENERS__WS__DEFAULT=marked_for_deletion
      - EMQX_LISTENERS__WSS__DEFAULT=marked_for_deletion
    privileged: true
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 90s
    sysctls:
      net.core.somaxconn: 32768
      net.ipv4.tcp_syncookies: 0
      net.ipv4.tcp_max_syn_backlog: 16384
      net.ipv4.tcp_max_tw_buckets: 1048576
      net.ipv4.tcp_fin_timeout: 15
      net.ipv4.ip_local_port_range: "1024 65535"
    ulimits:
      nproc: 1048576
      nofile:
        soft: 1048576
        hard: 1048576
    mem_limit: 512M
    cpus: 1.0
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
